"""add_email_to_user_and_access_code

Revision ID: 18b3f9237891
Revises: 7e0d385e1fe8
Create Date: 2026-07-13 23:22:22.167834
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b3f9237891'
down_revision: str | None = '7e0d385e1fe8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_codes', sa.Column('email', sa.String(length=255), nullable=True))
    op.drop_column('chat_messages', 'input_tokens')
    op.drop_column('chat_messages', 'output_tokens')
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.add_column('chat_messages', sa.Column('output_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chat_messages', sa.Column('input_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('access_codes', 'email')
    # ### end Alembic commands ###
