"""add_current_session_id_to_users

Revision ID: 2ff204cc3dfa
Revises: 3f35c758f34a
Create Date: 2026-08-21 20:30:40.619477
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2ff204cc3dfa"
down_revision: str | None = "3f35c758f34a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

__all__ = ["revision", "down_revision", "branch_labels", "depends_on"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("current_session_id", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "current_session_id")
    # ### end Alembic commands ###
