"""add_token_columns_to_chat_messages

Revision ID: 3ae9959e633d
Revises: 4f7d68350858
Create Date: 2026-07-10 08:00:13.029310
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ae9959e633d"
down_revision: str | None = "18b3f9237891"
branch_labels: str | Sequence[str] | None = None

depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_messages", sa.Column("input_tokens", sa.Integer(), nullable=True)
    )
    op.add_column(
        "chat_messages", sa.Column("output_tokens", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_messages", "output_tokens")
    op.drop_column("chat_messages", "input_tokens")
    # ### end Alembic commands ###
