"""add_indexes_for_performance

Revision ID: 3f35c758f34a
Revises: c2385d52f497
Create Date: 2026-08-19 10:16:42.531784
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f35c758f34a"
down_revision: str | None = "c2385d52f497"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_daily_recall_queue_topic_id"),
        "daily_recall_queue",
        ["topic_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_recall_queue_user_id"),
        "daily_recall_queue",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_topic_reviews_topic_id"), "topic_reviews", ["topic_id"], unique=False
    )
    op.create_index(
        op.f("ix_topic_reviews_user_id"), "topic_reviews", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_topic_reviews_user_id"), table_name="topic_reviews")
    op.drop_index(op.f("ix_topic_reviews_topic_id"), table_name="topic_reviews")
    op.drop_index(
        op.f("ix_daily_recall_queue_user_id"), table_name="daily_recall_queue"
    )
    op.drop_index(
        op.f("ix_daily_recall_queue_topic_id"), table_name="daily_recall_queue"
    )
    # ### end Alembic commands ###
