"""initial_schema

Revision ID: 8374cdf6b920
Revises: 
Create Date: 2026-06-28 13:03:54.747475
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8374cdf6b920'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_reviews', sa.Column('ease_factor', sa.Float(), nullable=False))
    op.drop_column('topic_reviews', 'ef')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_reviews', sa.Column('ef', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('topic_reviews', 'ease_factor')
    # ### end Alembic commands ###
