"""add_school_classes_and_user_class_id

Revision ID: c2385d52f497
Revises: b2c3d4e5f6a7
Create Date: 2026-08-19 08:37:49.783846
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c2385d52f497"
down_revision: str | None = "b2c3d4e5f6a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "school_classes",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("school_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "name", name="uq_school_class_name"),
    )
    op.add_column("users", sa.Column("class_id", sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(
        None, "users", "school_classes", ["class_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "class_id")
    op.drop_table("school_classes")
    # ### end Alembic commands ###
