# Mapping of domain exception error codes to HTTP status codes.
from fastapi import status

ERROR_STATUS_MAP: dict[str, int] = {
    # Authentication & Authorization
    "UNAUTHORIZED": status.HTTP_401_UNAUTHORIZED,
    "INVALID_TOKEN": status.HTTP_401_UNAUTHORIZED,
    "TOKEN_EXPIRED": status.HTTP_401_UNAUTHORIZED,
    "AUTHENTICATION_ERROR": status.HTTP_401_UNAUTHORIZED,
    "INVALID_CREDENTIALS": status.HTTP_401_UNAUTHORIZED,
    "FORBIDDEN": status.HTTP_403_FORBIDDEN,
    "PERMISSION_DENIED": status.HTTP_403_FORBIDDEN,
    "ACCOUNT_INACTIVE": status.HTTP_403_FORBIDDEN,
    "ACCOUNT_LOCKED": status.HTTP_429_TOO_MANY_REQUESTS,
    "TOO_MANY_ATTEMPTS": status.HTTP_429_TOO_MANY_REQUESTS,
    # Validation & Input Errors
    "VALIDATION_ERROR": status.HTTP_422_UNPROCESSABLE_ENTITY,
    "INVALID_INPUT": status.HTTP_422_UNPROCESSABLE_ENTITY,
    "BAD_REQUEST": status.HTTP_400_BAD_REQUEST,
    "INVALID_OTP": status.HTTP_400_BAD_REQUEST,
    "INVALID_RESET_CODE": status.HTTP_400_BAD_REQUEST,
    "RESET_TOKEN_EXPIRED": status.HTTP_400_BAD_REQUEST,
    "PASSWORD_REUSE_ERROR": status.HTTP_400_BAD_REQUEST,
    "NO_FIELDS_TO_UPDATE": status.HTTP_400_BAD_REQUEST,
    "INVALID_DATE_RANGE": status.HTTP_400_BAD_REQUEST,
    # Resource Errors
    "NOT_FOUND": status.HTTP_404_NOT_FOUND,
    "RESOURCE_NOT_FOUND": status.HTTP_404_NOT_FOUND,
    # Conflict & Duplicate Errors
    "RESOURCE_EXISTS": status.HTTP_409_CONFLICT,
    "DUPLICATE_ENTRY": status.HTTP_409_CONFLICT,
    "USER_ALREADY_REGISTERED": status.HTTP_409_CONFLICT,
    "REGISTRATION_PENDING": status.HTTP_409_CONFLICT,
    "RESOURCE_LOCKED": status.HTTP_423_LOCKED,
    # Rate Limiting
    "RATE_LIMIT_EXCEEDED": status.HTTP_429_TOO_MANY_REQUESTS,
    # Payment & Billing
    "BILLING_ERROR": status.HTTP_402_PAYMENT_REQUIRED,
    "PAYMENT_STATUS_ERROR": status.HTTP_400_BAD_REQUEST,
    "GATEWAY_ERROR": status.HTTP_502_BAD_GATEWAY,
    # Webhook
    "INVALID_WEBHOOK_SIGNATURE": status.HTTP_400_BAD_REQUEST,
    # Server Errors
    "INTERNAL_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "PROCESSING_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "INTERNAL_SERVER_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    # Service Availability
    "SERVICE_UNAVAILABLE": status.HTTP_503_SERVICE_UNAVAILABLE,
    "DEPENDENCY_ERROR": status.HTTP_503_SERVICE_UNAVAILABLE,
    "NETWORK_ERROR": status.HTTP_503_SERVICE_UNAVAILABLE,
    # Timeout
    "TIMEOUT": status.HTTP_504_GATEWAY_TIMEOUT,
    # Method
    "METHOD_NOT_ALLOWED": status.HTTP_405_METHOD_NOT_ALLOWED,
}
